### ISSUE TITLE
[Bug] Motivation hexagon shadow cut off

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/website#26]
## Short description
Shadows of motivation hexagons cut off.

## :heavy_check_mark: Expected behaviour
The shadow of each motivation hexagon (i.e. Who, Why, Fun) should be fully visible.

## ⚡ Actual behaviour 
On the bottom of each hexagon the shadow is cut off, because the padding / space allocated for the hexagon is not large enough.

**Screenshots**
![image](https://user-images.githubusercontent.com/37665562/97186052-1b4aea00-17a1-11eb-8c5a-8a027b4315f4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 86

## :joystick: Steps to reproduce
Provide a step by step list on how to reproduces the issue
1. Go to 'https://campus-community.org/'
2. Scroll down to 'Who, Why, Fun'

**Comment by Dominik-MCC** [comment]
Worked on that issue, will be closed

**Comment by Dominik-MCC** [comment]
Fixed in Commit 27eb7c8
