### ISSUE TITLE
[Bug] Responsiveness of motivation hexagon and its text

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/website#27]
## Short description
The right to motivation hexagon overlaps with the hexagon when the screen is between desktop size and phone size.

## :heavy_check_mark: Expected behaviour
The hexagon should already switch above the text for large than phone and smaller than desktop (i.e. tablets) screens.

## ⚡ Actual behaviour 
On screens with size in (654, 840) px the text to the right of the hexagon overlaps with the hexagon.

**Screenshots**
![image](https://user-images.githubusercontent.com/37665562/97187205-85b05a00-17a2-11eb-9381-749af9b0f49b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 86

## :joystick: Steps to reproduce
Provide a step by step list on how to reproduces the issue
1. Go to 'https://campus-community.org/'
2. Scroll down to 'Why, Who, Fun'
3. Change screen width to between 654px and 840px.

**Comment by Dominik-MCC** [comment]
Worked on that issue, will be closed

**Comment by Dominik-MCC** [comment]
Fixed in Commit 27eb7c8
