### ISSUE TITLE
[Bug] Numbers for steps in how to join

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/website#30]
## Short description
Try out how numbers inside hexagons looks.

## :heavy_check_mark: Expected behaviour
It might look good to have the numbers 1, 2 and 3 inside each of the three hexagons.

## ⚡ Actual behaviour 
Hexagons in "How to join" section are currently empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/37665562/97188929-5864ab80-17a4-11eb-8f58-d59151252bfc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 86

## :joystick: Steps to reproduce
Provide a step by step list on how to reproduces the issue
1. Go to 'https://campus-community.org/'
2. Scroll down to How to join'
3. See error

**Comment by Dominik-MCC** [comment]
Resolved with commit 79b57ec.
