### ISSUE TITLE
[Feature request] Close button for menu on mobile

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/website#31]
## :mag_right: Short desciption
Add functionality to close menu on mobile.

## :ticket: Detailed description
When I open the menu on a mobile device I must navigate to a different page or at least reload the page. Furthermore, might not be obvious to click on the MCC logo to stay on the home page when the menu is open.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I accidentally open the menu and don't know how to close it.

**Describe the solution you'd like**
Turn the hamburger button into a close button when the menu on mobile is open. The close button should close the menu stying on the same page without reloading.

**Describe alternatives you've considered**
Leaving as is because we are all smart enough to find a way to close the menu?

**Comment by Dominik-MCC** [comment]
@MalteRei You can always use the "back" button to close the menu, but we will implement the closing anyway.

**Comment by Dominik-MCC** [comment]
Fixed in Commit 27eb7c8 (on index only)

**Comment by Dominik-MCC** [comment]
Fixed in Commit e8cbd1b
