### ISSUE TITLE
[Bug] Change address 

### ISSUE THREAD

**Issue by MalteRei** [microsoft-campus-community/website#32]
## Short description
Currently the address in the footer, legal and privacy page is Heßstrasse 50.

## :heavy_check_mark: Expected behaviour
The address should be changed to 

> Walter-Gropius Straße 5, 80807 Munich

**Screenshots**
![image](https://user-images.githubusercontent.com/37665562/97190969-aaa6cc00-17a6-11eb-8a8f-0021b1f7764c.png)
![image](https://user-images.githubusercontent.com/37665562/97190982-af6b8000-17a6-11eb-98a2-a9378bb2c466.png)
![image](https://user-images.githubusercontent.com/37665562/97190992-b2667080-17a6-11eb-88cd-f8da32bf1401.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 86

## :joystick: Steps to reproduce
Provide a step by step list on how to reproduces the issue
1. Go to 'https://campus-community.org/'
2. Scroll all the way down
3. See error
4. Go to 'https://campus-community.org/legal'
5. Scroll to 'Angaben gemäß §5 TMG'
6. See error
7. Go to 'https://campus-community.org/privacy.html'
8. Scroll to 'Name und Kontaktdaten des / der Verantwortlichen'
9. See error

**Comment by Dominik-MCC** [comment]
Fixed in Commit 27eb7c8
